# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9207ed6818b08affa4a5912cba93f8393d6f00c10c3d86f47319f9e4beddc1eaa565240c0344c635bae6f34870dcdae3dd7e3d4051265754887aefa060e7601

test:
  secret_key_base: d5a86c737f772e8821aa1f61d573b00971dc2662fb433c289db5ced2b54a673daeb743b99ea21e331b8df3424461fa49c50f1e81132a25dfd56e9e2ebbd0f927

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
